apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: efk
  labels:
    component: kibana
spec:
  type: LoadBalancer
  selector:
    app: v1-kibana
  ports:
  - port: 80
    protocol: "TCP"
    name: "http"
    targetPort: 5601