apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret-prod
  namespace: efk
spec:
  secretName: tls-secret-prod
  dnsNames:
  - efk-recipesavants.northcentralus.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - efk-recipesavants.northcentralus.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer