apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: route-ingress-prod
  namespace: efk
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - efk-recipesavants.northcentralus.cloudapp.azure.com
    secretName: tls-secret-prod
  rules:
  - host: efk-recipesavants.northcentralus.cloudapp.azure.com
    http:
      paths:     
      - path: /
        backend:
          serviceName: kibana-logging
          servicePort: 5601
      - path: /elasticsearch/.*
        backend:
          serviceName: elasticsearch-logging
          servicePort: 9200
      - path: /redis
        backend:
          serviceName: redis-service
          servicePort: 6379
      